### ISSUE TITLE
Don't fail the entire apply when one of the dashboards failed to apply

### ISSUE THREAD

**Issue by noym94** [SupersonicAds/gdbt#5]
When running apply to a bunch of changes at the same time, if one of them fails the entire apply fails.

Example:
``` 
Pending changes:
- Dashboard aerospike-metrics_test will be removed:
  - folder:   "gdbt_77ff1b6272458267e0f1085785451561"
  - grafana:  "grafana"
  - model:    "{'annotations': {'list': [{'builtIn': 1, 'datasource': '-- Grafa..."
  - uid:      "gdbt_64d3903ff3c5875c74948bf0ceff071a"
- Dashboard host-reachability_i-0907e0fcd43d370ea will be removed:
  - folder:   "gdbt_7bdbc9d0626b25091a80de0aeaff3ec5"
  - grafana:  "grafana"
  - model:    "{'annotations': {'list': [{'builtIn': 1, 'datasource': '-- Grafa..."
  - uid:      "gdbt_98c6d76915ddcd79afa0605153cd0edd"
+ Dashboard host-reachability_i-0d295ee30387fe26f will be created:
  + folder:   "gdbt_7bdbc9d0626b25091a80de0aeaff3ec5"
  + grafana:  "grafana"
  + model:    "{'annotations': {'list': [{'builtIn': 1, 'datasource': '-- Grafa..."
  + uid:      "gdbt_c1ff7bc85d36167f202038cdf855511e"
Apply? [y/N]: y
ERROR [ERR_GRAFANA]: Grafana API error: Client Error 404: Dashboard not found
```

In this case, `Dashboard aerospike-metrics_test will be removed` and `Dashboard host-reachability_i-0907e0fcd43d370ea will be removed` didn't apply because `Dashboard host-reachability_i-0d295ee30387fe26f will be created` failed.

**Suggestion**
Fail only one of the dashboard's apply, but apply the rest of them. If something has failed it will be visible later when running `plan` and seeing that the diff is still there. Also, an error like the above is great.

**Comment by zerodayyy** [comment]
This needs to be re-assessed due to usage of threads in GDBT 2.0.0, which means that exceptions no longer stop the execution

**Comment by noym94** [comment]
> This needs to be re-assessed due to usage of threads in GDBT 2.0.0, which means that exceptions no longer stop the execution

we can close this @zerodayyy :)
